# Generated by Django 2.2.16 on 2020-09-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('calories', models.PositiveIntegerField(help_text='в 100 граммах', verbose_name='Количество калорий')),
            ],
            options={
                'verbose_name': ('Продукт',),
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
    ]
