# Generated by Django 2.2.16 on 2020-09-10 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_auto_20200909_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='grams',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество грамм'),
        ),
        migrations.CreateModel(
            name='DishRation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ration', to='dishes.Dish')),
            ],
            options={
                'verbose_name': 'Блюдо в рационе',
                'verbose_name_plural': 'Блюда в рационе',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='ration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='dishes.DishRation'),
        ),
    ]
